# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'test.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtWidgets


class Ui_TransferWidget(object):
    def setupUi(self, TransferWidget):
        TransferWidget.setObjectName("TransferWidget")
        TransferWidget.resize(400, 549)
        self.verticalLayout = QtWidgets.QVBoxLayout(TransferWidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.host_label = QtWidgets.QLabel(TransferWidget)
        self.host_label.setMaximumSize(QtCore.QSize(382, 15))
        self.host_label.setObjectName("host_label")
        self.verticalLayout.addWidget(self.host_label)
        self.host_input = QtWidgets.QLineEdit(TransferWidget)
        self.host_input.setMaximumSize(QtCore.QSize(382, 22))
        self.host_input.setObjectName("host_input")
        self.verticalLayout.addWidget(self.host_input)
        self.username_label = QtWidgets.QLabel(TransferWidget)
        self.username_label.setMaximumSize(QtCore.QSize(382, 15))
        self.username_label.setObjectName("username_label")
        self.verticalLayout.addWidget(self.username_label)
        self.username_input = QtWidgets.QLineEdit(TransferWidget)
        self.username_input.setMaximumSize(QtCore.QSize(382, 22))
        self.username_input.setObjectName("username_input")
        self.verticalLayout.addWidget(self.username_input)
        self.private_key_pass_label = QtWidgets.QLabel(TransferWidget)
        self.private_key_pass_label.setMaximumSize(QtCore.QSize(382, 15))
        self.private_key_pass_label.setObjectName("private_key_pass_label")
        self.verticalLayout.addWidget(self.private_key_pass_label)
        self.private_key_pass_input = QtWidgets.QLineEdit(TransferWidget)
        self.private_key_pass_input.setMaximumSize(QtCore.QSize(382, 22))
        self.private_key_pass_input.setEchoMode(QtWidgets.QLineEdit.Password)
        self.private_key_pass_input.setObjectName("private_key_pass_input")
        self.verticalLayout.addWidget(self.private_key_pass_input)
        self.private_key_dir_label = QtWidgets.QLabel(TransferWidget)
        self.private_key_dir_label.setMaximumSize(QtCore.QSize(382, 15))
        self.private_key_dir_label.setObjectName("private_key_dir_label")
        self.verticalLayout.addWidget(self.private_key_dir_label)
        self.private_key_dir_input = QtWidgets.QLineEdit(TransferWidget)
        self.private_key_dir_input.setMaximumSize(QtCore.QSize(382, 22))
        self.private_key_dir_input.setObjectName("private_key_dir_input")
        self.verticalLayout.addWidget(self.private_key_dir_input)
        self.private_key_dir_button = QtWidgets.QPushButton(TransferWidget)
        self.private_key_dir_button.setMaximumSize(QtCore.QSize(382, 23))
        self.private_key_dir_button.setObjectName("private_key_dir_button")
        self.verticalLayout.addWidget(self.private_key_dir_button)
        self.ignore_host_key_checkbox = QtWidgets.QCheckBox(TransferWidget)
        self.ignore_host_key_checkbox.setMaximumSize(QtCore.QSize(382, 21))
        self.ignore_host_key_checkbox.setChecked(True)
        self.ignore_host_key_checkbox.setObjectName("ignore_host_key_checkbox")
        self.verticalLayout.addWidget(self.ignore_host_key_checkbox)
        self.source_dir_label = QtWidgets.QLabel(TransferWidget)
        self.source_dir_label.setMaximumSize(QtCore.QSize(382, 15))
        self.source_dir_label.setObjectName("source_dir_label")
        self.verticalLayout.addWidget(self.source_dir_label)
        self.source_dir_input = QtWidgets.QLineEdit(TransferWidget)
        self.source_dir_input.setMaximumSize(QtCore.QSize(382, 22))
        self.source_dir_input.setObjectName("source_dir_input")
        self.verticalLayout.addWidget(self.source_dir_input)
        self.source_dir_button = QtWidgets.QPushButton(TransferWidget)
        self.source_dir_button.setMaximumSize(QtCore.QSize(382, 23))
        self.source_dir_button.setObjectName("source_dir_button")
        self.verticalLayout.addWidget(self.source_dir_button)
        self.target_dir_label = QtWidgets.QLabel(TransferWidget)
        self.target_dir_label.setMaximumSize(QtCore.QSize(382, 15))
        self.target_dir_label.setObjectName("target_dir_label")
        self.verticalLayout.addWidget(self.target_dir_label)
        self.target_dir_input = QtWidgets.QLineEdit(TransferWidget)
        self.target_dir_input.setMaximumSize(QtCore.QSize(382, 22))
        self.target_dir_input.setObjectName("target_dir_input")
        self.verticalLayout.addWidget(self.target_dir_input)
        self.save_config_button = QtWidgets.QPushButton(TransferWidget)
        self.save_config_button.setMaximumSize(QtCore.QSize(382, 23))
        self.save_config_button.setObjectName("save_config_button")
        self.verticalLayout.addWidget(self.save_config_button)
        self.load_config_button = QtWidgets.QPushButton(TransferWidget)
        self.load_config_button.setMaximumSize(QtCore.QSize(382, 23))
        self.load_config_button.setObjectName("load_config_button")
        self.verticalLayout.addWidget(self.load_config_button)
        self.clear_config_button = QtWidgets.QPushButton(TransferWidget)
        self.clear_config_button.setMaximumSize(QtCore.QSize(382, 23))
        self.clear_config_button.setObjectName("clear_config_button")
        self.verticalLayout.addWidget(self.clear_config_button)
        self.upload_button = QtWidgets.QPushButton(TransferWidget)
        self.upload_button.setMaximumSize(QtCore.QSize(382, 23))
        self.upload_button.setObjectName("upload_button")
        self.verticalLayout.addWidget(self.upload_button)

        self.retranslateUi(TransferWidget)
        QtCore.QMetaObject.connectSlotsByName(TransferWidget)

    def retranslateUi(self, TransferWidget):
        _translate = QtCore.QCoreApplication.translate
        TransferWidget.setWindowTitle(_translate("TransferWidget", "Transfer Data"))
        self.host_label.setText(_translate("TransferWidget", "Target IP:"))
        self.username_label.setText(_translate("TransferWidget", "Target Username:"))
        self.private_key_pass_label.setText(
            _translate("TransferWidget", "Target Password:")
        )
        self.private_key_dir_label.setText(
            _translate("TransferWidget", "Private Key Directory:")
        )
        self.private_key_dir_button.setText(_translate("TransferWidget", "Browse"))
        self.ignore_host_key_checkbox.setText(
            _translate("TransferWidget", "Ignore Host Key")
        )
        self.source_dir_label.setText(_translate("TransferWidget", "Source Directory:"))
        self.source_dir_button.setText(_translate("TransferWidget", "Browse"))
        self.target_dir_label.setText(_translate("TransferWidget", "Target Directory:"))
        self.target_dir_input.setText(_translate("TransferWidget", "/home/"))
        self.save_config_button.setText(_translate("TransferWidget", "Save Config"))
        self.load_config_button.setText(_translate("TransferWidget", "Load Config"))
        self.clear_config_button.setText(_translate("TransferWidget", "Clear Config"))
        self.upload_button.setText(_translate("TransferWidget", "Upload"))


if __name__ == "__main__":
    import sys

    app = QtWidgets.QApplication(sys.argv)
    TransferWidget = QtWidgets.QWidget()
    ui = Ui_TransferWidget()
    ui.setupUi(TransferWidget)
    TransferWidget.show()
    sys.exit(app.exec_())
