# Save the output of this file and use kubectl create -f to import
# it into Kubernetes.

#Use this file to create a Persistent Volume Claim before running team4_lamp_k8s.yaml

# Created with podman-3.4.4
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  annotations:
    volume.podman.io/driver: local
  creationTimestamp: "2023-02-14T20:14:05Z"
  name: notebook-pvc
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
status: {}
