# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python application

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    container: python:3.13-slim
    
    steps:
      - uses: actions/checkout@v4
      - name: Install R
        run: |
          apt-get update
          apt-get install -y --no-install-recommends software-properties-common dirmngr gnupg ca-certificates
          echo "deb https://cloud.r-project.org/bin/linux/debian bookworm-cran40/" > /etc/apt/sources.list.d/cran.list
          apt-key adv --keyserver keyserver.ubuntu.com --recv-keys '06F90DE5381BA480'
          apt-get update
          apt-get install -y --no-install-recommends r-base
          R --version && Rscript --version
      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Lint
        run: |
          flake8 . --exclude "Legacy*,venv,.venv"
      - name: Test
        run: |
          pytest --ignore-glob='Legacy*' --ignore=venv --ignore=.venv